### ISSUE TITLE
File compare always showing different ending

### ISSUE THREAD

**Issue by Antes** [WinMerge/winmerge-v2#106]
This marks all files different even they are identical. All settings are set to default, no custom regex/white-space command added.

Version: 2.15.5.0 - Unicode x64

https://gyazo.com/d4631094df1b1047d722ab4818812439

**Comment by sdottaka** [comment]
Fixed in 1b52d8491a0c3c0e9bad1daa0fa586c49c9af75d. Thank you for the report.
