### ISSUE TITLE
Updated brazilian portuguese translation plus report

### ISSUE THREAD

**Issue by Felipefpl** [WinMerge/winmerge-v2#108]
Hi, i am Felipe and here is an update i made for the translation i made more than 9 years ago (it's good to see winmerge back after so many years inactive). It's for Winmerge 2.16.0.0.

I want to report that there are 2 entries for brazilian portuguese in the translation's page, the empty one can be removed without any problem. ;)

The dialog box for the settings needs to be able to auto-resize itself to become bigger to give space for translated words that many times are bigger in brazilian portuguese or other languages, several phrases can't be fully seen.

[Brazilian.zip](https://github.com/WinMerge/winmerge-v2/files/2636255/Brazilian.zip)

**Comment by sdottaka** [comment]
Thank you for the translation!
Applied in 1f702cb601eca0f6e854a5de1de9bfbb7d79a83e

The two problems has been fixed in b9e7454a2a8cf218d778e5326c8bef2e78913ce3 and 2b597edcc59882d350fda3a44dea7cd227c049c0

**Comment by Felipefpl** [comment]
Thanks for the fixes but i want to make a report about this:

https://github.com/WinMerge/winmerge-v2/commit/b9e7454a2a8cf218d778e5326c8bef2e78913ce3

About the 2 entries i was talking about the translators' board that contains those entries here:

http://winmerge.org/translations/ ;)

**Comment by sdottaka** [comment]
@gerundt Thank you for updating the page!

**Comment by Lippe35** [comment]
@sdottaka @gerundt this is not importante but portuguese have two variants

Português (Brasil) 
Português (Portugal)

https://drive.google.com/open?id=1bVIEEmFs6Nk7BbLmAQHBYUEckmKKarhT

**Comment by sdottaka** [comment]
@Lippe35 You mean we should rename the 'Brazilian' entry to 'Brazilian Portuguese' or a similar one?

**Comment by Lippe35** [comment]
@sdottaka my suggestion is:

Português (Brasil)
Português (Portugal)

**Comment by gerundt** [comment]
We use internal still the englisch names. Maybe switching to ISO codes instead?
* PT_BR
* PT_PT

Or keep it like the last years. ;-)

**Comment by Lippe35** [comment]
@gerundt https://support.microsoft.com/pt-pt/help/14236/language-packs

PT_BR
PT_PT

Its ok is short local designation :-)

**Comment by sdottaka** [comment]
The translation page is created by https://github.com/WinMerge/winmerge-v2/blob/master/Translations/GetTranslationsStatus.py.

Pull requests are welcome!
