### ISSUE TITLE
CreateTranslatedRcFiles needs an update

### ISSUE THREAD

**Issue by pgert** [WinMerge/winmerge-v2#113]
"CreateTranslatedRcFiles" seems to expect that the PO-file from which it is to make the RC-file ends with double-return (a blank line), followed by a NULL-terminator. Otherwise it won't translate the last string, but instead use the original (english) text for that string. At least on newer versions of PO-edit, this double-return is not made. Can't make out anything of the VB-script myself.

**Comment by sdottaka** [comment]
Fixed in 46fe00a. Thank you for the report!
