### ISSUE TITLE
Invalid by default the 3rd File or Folder Option and hide Compare button 

### ISSUE THREAD

**Issue by ALanMAttano** [WinMerge/winmerge-v2#117]
**Issue:** When calling WinMerge using Unity Collab button,
The default 3rd File or Folder Option is invalid. The field contains "U:\e" as for example.  
And is difficult for a beginner to understand why the Compare button is not working since is deactivated. 

**Solution:** in the input field replace "U:\e" with an empty string by default.
![option](https://user-images.githubusercontent.com/8115739/50388095-0c013e00-06eb-11e9-962d-8b3981f2b4e5.jpg)

**Comment by sdottaka** [comment]
I think this is not a problem with WinMerge but a problem with Unity.
As shown in the attached file, the command line option for starting WinMerge from Unity is invalid. (For example, `\e` must be `/e` or `-e`
![unity](https://user-images.githubusercontent.com/98126/50400880-cbc6bc00-07cd-11e9-99f4-35b40fe97fe1.png)
)

**Comment by ALanMAttano** [comment]
Ok, I make a bug report to Unity. 
[https://forum.unity.com/threads/bug-invalid-command-line-using-collaborate-and-winmerge.603064/]
You can close
