### ISSUE TITLE
Visual Studio merge is not working with version 2.16.0

### ISSUE THREAD

**Issue by CodeTroopers** [WinMerge/winmerge-v2#133]
After configuring Visual Studio with Visual Studio Team Foundation Server to merge with WinMerge
![image](https://user-images.githubusercontent.com/5825215/53233047-b0bcdf00-368c-11e9-9ca9-c93cd773c078.png)
A merging operation opens a window with three path
![image](https://user-images.githubusercontent.com/5825215/53233379-8fa8be00-368d-11e9-8801-da08e6f8e9e2.png)
But the third path is invalid because the file doesn't exist yet... and the merge operation can not be do
This configuration worked with an older version of winmerge (I can't tell what version)

**Comment by sdottaka** [comment]
The command line argument of version 2.16.0 is partially incompatible with that of version 2.14.0.

The third argument is used as the third file in 3-way diff or merge.

If you want to do the same behavior as 2.14.0, use / o% 4 instead.

**Comment by CodeTroopers** [comment]
[The documentation](http://manual.winmerge.org/Command_line.html) is not uptodate.

**Comment by sdottaka** [comment]
@CodeTroopers Please refer .chm help instead.

@gerundt Are you accessible to manual.winmerge.org and updatable the documents?
If you don't have access to manual.winmerge.org, could you move the documents to an accessible place?

**Comment by gerundt** [comment]
The web manual should be now up-to-date. 👍

**Comment by CodeTroopers** [comment]
You could have a sub directory by version for the documentation because browser cache displays the documentation of version 2.14

**Comment by sdottaka** [comment]
@gerundt  Thank you!
