### ISSUE TITLE
Publish 2.16.x release as actual release

### ISSUE THREAD

**Issue by jawn** [WinMerge/winmerge-v2#136]
Hello,

Thanks for having fixed this assertion bug in Winmerge: 
https://sourceforge.net/p/winmerge/bugs/2214/

I see it the fix is available in a preview version download (2.16.1 or .2)

However, would it be possible to release a hotfix version for this kind of blocking errors? Many regular users don't drill down into preview versions and will either stop using the product or log the issue again.

I understand this is an open source project and appreciate the community efforts.

If a release is coming very soon, please ignore this message :)

Thanks,

Bernard

**Comment by sdottaka** [comment]
I will release version 2.16.2 in early April.

**Comment by jawn** [comment]
I see this is done, thanks!

**Comment by Gitoffthelawn** [comment]
Just FYI, http://winmerge.org/downloads/ has yet to be updated.

**Comment by gerundt** [comment]
The website should now also up-to-date.
