### ISSUE TITLE
Temporary files could not be created

### ISSUE THREAD

**Issue by bardware** [WinMerge/winmerge-v2#143]
I repeatedly got the error message `Temporary files could not be created. Check your temporary path settings.`
What is the reason for this error?
I close WinMerge, open again and it works.
I just don't want to close WinMerge every time, because I have compares open I'd like to keep for the moment.

![grafik](https://user-images.githubusercontent.com/802702/57316338-da1ad200-70f5-11e9-96bc-71091dd12327.png)

Thanks for keeping the project alive and releasing new Versions, :thumbsup:
Bernhard

**Comment by sdottaka** [comment]
Fixed by commit https://bitbucket.org/winmerge/winmerge/commits/dfc6e51176c095e91939ac8a98db26ceae7970e6

Thank you for the report.

The latest CI artifacts are available at https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts

**Comment by bardware** [comment]
I'll look at it. Thanks alot.
