### ISSUE TITLE
file compare : right-click doesn't select the diff under the mouse

### ISSUE THREAD

**Issue by ian-weatherhogg-refractiv** [WinMerge/winmerge-v2#159]
...so if i choose "Copy to left/right", it can copy a diff from elsewhere in the file.

**Comment by sdottaka** [comment]
Fixed by commit 6a14cf5ef4f51c9f6ff9da90830573893ca5e4d0

Thank you for the report.

The latest CI build artifacts are available at https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts
