### ISSUE TITLE
Installer - Proposal - Separate Inno Setup strings from WinMerge installer strings

### ISSUE THREAD

**Issue by bovirus** [WinMerge/winmerge-v2#167]
@sdottaka 

I propose you to modify the installer script and .ISL language files.

Currently ISL language files contains both base Inno Setup language common strings and dedicated strings for WinMerge installer.

I propose you to separate standard ISL language strings from WinMerge installer strings.

Than for each language you will have

- File for standard ISS language common strings (equal to the .ISL language file available in Inno Setup repository)
- File for additional WinMerge installer strings.

Then you can manage it separately.

If you get a new or updated ISL language file in Inno Setup repository you copy it.
Without touching WinMerge installer strings.

If you have to add/revise WinMerge installer strings you can do it without touching Inno Setup installer strings.

**Comment by sdottaka** [comment]
Implemeted by commit a63c72bbb9d0df5139d9fb30fef23cbaad0fa95c

Thank you for the proposal.

**Comment by Tichij** [comment]
@sdottaka,
And why was it not adapted to all languages (e.g. lithuanian)?

**Comment by bovirus** [comment]
@Tichij 

Probably should be updated soon.
The same problem appera for

Basque
Bulgarian
Chinese simplified
Galician
Greek
Hungarian
Korean
Lithuanian
Romanian
Serbian
Sinhala
Slovak
Swedish

@sdottaka 

Please complete the update language process using the same scheme for the languages listed.

If the Inno Setup ISL language are not included as base you can create from your current file on repository splitting the current file in one file for Inno Setup (that you copy in your Inno Setup installation folder) and one small file for custom messages (that are only for WinMerge).
Thanks.

**Comment by sdottaka** [comment]
Currently, the separation has been done only for the languages ​​bundled with InnoSetup 6.02.
Because the base part can be removed from the WinMerge repository, as long as the language is bundled with InnoSetup.
Of course, it is possible to separate .isl file on languages ​​not bundled with InnoSetup, so I will try to work later.

**Comment by bovirus** [comment]
@sdottaka

It's exactly what I mentioned.
Thanks in advance.

**Comment by bovirus** [comment]
@Tichij 

I suggest you to check (ex. Lithuanian), update it and upload it on Inno Setup repositories to have it included in next release.

**Comment by Tichij** [comment]
@bovirus, @sdottaka 
Lithuanian translation (compatible with 6.0.2 version) already in Inno Setup repository from Mar 1 2019:
https://github.com/jrsoftware/issrc/blob/master/Files/Languages/Unofficial/Lithuanian.isl

**Comment by sdottaka** [comment]
@Tichij Lithuanian.isl file is in Unofficial folder. I think the files in Unofficial folder are not included with the InnoSetup installer. When installing InnoSetup 6.0.2, you will find that Lithuanian.isl is not installed in InnoSetup 6\Languages ​​folder.

**Comment by sdottaka** [comment]
The separation of all languages has been done by commit 
2d23aff
