### ISSUE TITLE
Suspicious lack of Release() calls in lwdisp.c

### ISSUE THREAD

**Issue by Dmitry-Me** [WinMerge/winmerge-v2#171]
In lwdisp.c function invokeV():
1. calls GetTypeInfo() to obtain a `ITypeInfo*` pointer but never calls `Release()` via that pointer.
2. calls ITypeInfo::QueryInterface() to obtain a `ITypeInfo2*` pointer but never calls `Release()` via the obtained pointer.

This looks like a bug.

**Comment by sdottaka** [comment]
Fixed by commit d0831e366f29aca2bb9741e88cac5b886fe09e73
Thank you for the report

**Comment by Dmitry-Me** [comment]
@sdottaka The `Release()` call for `pTypeInfo2` is misplaced - it should be right inside `if (pTypeInfo2 != NULL)`.

**Comment by sdottaka** [comment]
Fixed by commit ca54fb5b7791da094a96da6147b80e6d5dbe6711

Thank you again.
